frontmatter:
  title:
    type: string
    required: true
    placeholder_message: Enter a title
    validation_message: Please ensure your article has a title
  author:
    type: email
    required: true
    placeholder_message: Enter author email
    validation_message: Please ensure your article has an author email address
